#   ____                                 ____         __ _
#  |  _ \ ___   __ _ _ __ ___   ___ _ __/ ___|  ___  / _| |_
#  | |_) / _ \ / _` | '_ ` _ \ / _ \ '__\___ \ / _ \| |_| __|
#  |  _ < (_) | (_| | | | | | |  __/ |   ___) | (_) |  _| |_
#  |_| \_\___/ \__,_|_| |_| |_|\___|_|  |____/ \___/|_|  \__|
#  ---------------------------------------------------------------
#  Frontend App - Angular - Docker Compose
#  ---------------------------------------------------------------

version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: frontend:roamersoft
    container_name: rsfe
    restart: always
    networks:
      - rsbe_default
    ports:
      - 8080:8080

networks:
  rsbe_default:
    external: true
